jwt:
  secret: tVy6/eiGjuZOlovDWkObVHEB60shGWjNBNCf9XdGNADDAc0LLswJuSuXv/BNzNEa2yiSZfXMKIJw6gNwed70/U29sjp/sDvuJy2E41erdHT+SSqoVCH5iA8tEooBcRqXvRQ1EJGLF/640KkuXUb3R7eIuV7XOj+zvOIJldugT7OFwc15nkUY0Oy2F04tKDfQi9UU8AgFOAd9dsOLHfFRS0cdq6pkF+QriPEmKKqmWjvCP7o4wt7Tt247ZaJ0gJgpxuGN3OjGc61N53eKznwHrwh9DH8oD1G5BaqHeBTdq6uqhei0v3LVfJpTFS3Tt5DOiBkDI5cnrHgbDMwGgDev
  expiration: 86400000  # 24 hours

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method   # sort theo GET/POST/PUT/DELETE
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0        # 1s → 2s → 4s
          max-interval: 10000ms  # maximum 10s between retries
        acknowledge-mode: auto

rabbitmq:
  exchange: booking.exchange
  queue:
    booking: booking.queue
    dead-letter: booking.dead-letter.queue
  routing-key:
    booking: booking.key
    dead-letter: booking.dead-letter.key
# Key conventions
redis:
  key:
    ticket-stock: "ticket_stock:"    # ticket_stock:{ticketId}
    order-status: "order_status:"    # order_status:{orderId}
  ttl:
    order-status: 3600  # 1 hour (seconds)


